language: objective-c
osx_image: xcode8.2
xcode_project: SwiftOrg.xcodeproj
xcode_scheme: SwiftOrg-iOS
env:
  global:
    - FRAMEWORK_NAME=SwiftOrg
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  - carthage bootstrap
script:
  - ./bin/test
before_deploy:
  - carthage build --no-skip-current
deploy:
  - provider: script
    script: ./bin/push
    on:
      branch: master
      tags: true
