osx_image: xcode8.2
language: objective-c
xcode_project: SwiftOrg.xcodeproj
script:
  - swift build
  - swift test
deploy:
  - provider: script
    script: ./scripts/publish
    on:
      branch: master
      tags: true
